# Generated by Django 2.1.15 on 2025-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_planta_correo'),
        ('usuarios', '0006_auto_20241121_0806'),
        ('clinico', '0096_auto_20241023_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicos',
            unique_together={('planta', 'tipoDoc', 'documento')},
        ),
    ]
