# Generated by Django 2.1.15 on 2025-01-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_planta_correo'),
        ('sitios', '0013_auto_20241115_1218'),
        ('clinico', '0098_auto_20250129_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especialidadesmedicos',
            unique_together={('sedesClinica', 'tiposPlanta', 'planta', 'especialidades')},
        ),
    ]
