# Generated by Django 2.1.15 on 2025-01-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0099_auto_20250129_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especialidadesmedicos',
            unique_together=set(),
        ),
    ]
