# Generated by Django 2.1.15 on 2025-01-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0013_auto_20241115_1218'),
        ('planta', '0005_planta_correo'),
        ('clinico', '0100_auto_20250129_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadesmedicos',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='especialidadesmedicos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica301', to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='especialidadesmedicos',
            name='tiposPlanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposPlanta301', to='planta.TiposPlanta'),
        ),
        migrations.AlterUniqueTogether(
            name='especialidadesmedicos',
            unique_together={('sedesClinica', 'tiposPlanta', 'planta', 'especialidades')},
        ),
    ]
