# Generated by Django 2.1.15 on 2025-01-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0101_auto_20250129_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='especialidadesMedicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EspecialidadesMedicos'),
        ),
    ]
