# Generated by Django 2.1.15 on 2025-01-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0102_historia_especialidadesmedicos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicos',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='especialidades',
        ),
    ]
