# Generated by Django 2.1.15 on 2025-01-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0103_auto_20250130_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='tipoDoc',
        ),
    ]
