# Generated by Django 2.1.15 on 2025-01-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0013_auto_20241115_1218'),
        ('planta', '0005_planta_correo'),
        ('clinico', '0105_auto_20250130_0808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especialidadesmedicos',
            unique_together={('sedesClinica', 'planta', 'especialidades')},
        ),
    ]
