# Generated by Django 2.1.15 on 2025-01-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0106_auto_20250130_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidadesmedicos',
            name='tiposPlanta',
        ),
    ]
