# Generated by Django 2.1.15 on 2025-02-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0003_auto_20240916_1100'),
        ('clinico', '0107_remove_especialidadesmedicos_tiposplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenes',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut01', to='autorizaciones.Autorizaciones'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut02', to='autorizaciones.Autorizaciones'),
        ),
    ]
