# Generated by Django 2.1.15 on 2025-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0108_auto_20250224_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='mipres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
