# Generated by Django 2.1.15 on 2025-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0109_auto_20250224_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiamedicamentos',
            name='orden',
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
