# Generated by Django 2.1.15 on 2025-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0110_auto_20250224_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenes',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historialincapacidades',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historiaoxigeno',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='trasfusiones',
            name='ordenMedica',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
