# Generated by Django 2.1.15 on 2025-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0112_historiamedicamentos_concentracionmedicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='mipres',
        ),
        migrations.AddField(
            model_name='historia',
            name='mipres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
