# Generated by Django 2.1.15 on 2025-02-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0113_auto_20250225_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenes',
            old_name='autorizar',
            new_name='requiereAutorizacion',
        ),
    ]
