# Generated by Django 2.1.15 on 2025-02-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0014_sedesclinica_codigohabilitacion'),
        ('clinico', '0114_auto_20250225_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica367', to='sitios.SedesClinica'),
        ),
    ]
