# Generated by Django 2.1.15 on 2025-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0115_historia_sedesclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='ordenMedica',
        ),
        migrations.RemoveField(
            model_name='historialincapacidades',
            name='ordenMedica',
        ),
        migrations.RemoveField(
            model_name='historiamedicamentos',
            name='ordenMedica',
        ),
        migrations.RemoveField(
            model_name='historiaoxigeno',
            name='ordenMedica',
        ),
        migrations.RemoveField(
            model_name='trasfusiones',
            name='ordenMedica',
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaInt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaLab',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaMed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaOxi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaRad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ordenMedicaTer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
