# Generated by Django 2.1.15 on 2025-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0116_auto_20250226_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenes',
            name='consecutivoLiquidacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='consecutivoLiquidacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
