# Generated by Django 2.1.15 on 2025-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0117_auto_20250325_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examenes',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='examenes',
            index=models.Index(fields=['nombre'], name='examenesNombreIdx'),
        ),
    ]
