# Generated by Django 2.1.15 on 2025-05-01 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0118_auto_20250414_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialincapacidades',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='historialincapacidades',
            name='desdeFecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='historialincapacidades',
            name='hastaFecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
