# Generated by Django 2.1.15 on 2025-05-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('clinico', '0120_auto_20250502_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='dependenciasRealizado',
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosAdministrativos'),
        ),
    ]
