# Generated by Django 2.1.15 on 2025-05-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0121_auto_20250502_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.GruposQx'),
        ),
    ]
