# Generated by Django 2.1.15 on 2025-05-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0122_auto_20250515_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='codigoCups',
            new_name='agenda',
        ),
        migrations.AddField(
            model_name='especialidades',
            name='citaDeControl',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='examenCita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuposCita', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='valoracionInicial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
