# Generated by Django 2.1.15 on 2025-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0123_auto_20250519_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiamedicamentos',
            name='item',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
