# Generated by Django 2.1.15 on 2025-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0124_historiamedicamentos_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiamedicamentos',
            name='consecutivoMedicamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
