# Generated by Django 2.1.15 on 2025-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0125_historiamedicamentos_consecutivomedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='frecuenciasaplicacion',
            name='numeroHoras',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
