# Generated by Django 2.1.15 on 2025-07-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0126_frecuenciasaplicacion_numerohoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDietas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dietas001g8', to='clinico.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDietas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='historialdietas',
            name='tipoDieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDietas001', to='clinico.TipoDietas'),
        ),
    ]
