# Generated by Django 2.1.15 on 2025-07-24 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0127_auto_20250724_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNotasEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=4000, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaEnfHistoria001', to='clinico.Historia')),
            ],
        ),
    ]
