# Generated by Django 2.1.15 on 2025-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0128_historialnotasenfermeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='ordenDeControl',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
