# Generated by Django 2.1.15 on 2025-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0129_historia_ordendecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='interpretacion1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='interpretacion2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
