# Generated by Django 2.1.15 on 2025-09-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0130_auto_20250909_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='medicoInterpretacion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta01', to='clinico.Medicos'),
        ),
    ]
