# Generated by Django 2.1.15 on 2025-09-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0131_auto_20250909_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='medicoInterpretacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta02', to='clinico.Medicos'),
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='medicoInterpretacion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta03', to='clinico.Medicos'),
        ),
    ]
