# Generated by Django 2.1.15 on 2025-09-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0132_auto_20250909_1631'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historia',
            index=models.Index(fields=['tipoDoc', 'documento', 'folio'], name='clinico_his_tipoDoc_68a6a6_idx'),
        ),
    ]
