# Generated by Django 2.1.15 on 2025-09-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0133_auto_20250910_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='especialidadConsulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espe22', to='clinico.EspecialidadesMedicos'),
        ),
    ]
