# Generated by Django 2.1.15 on 2025-09-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0134_auto_20250911_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espe22', to='clinico.Especialidades'),
        ),
    ]
