# Generated by Django 2.1.15 on 2025-09-12 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0135_auto_20250911_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinterconsultas',
            name='fechaRespuesta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
