# Generated by Django 2.1.15 on 2025-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0136_historialinterconsultas_fecharespuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='solicitaEnfermeria',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
