# Generated by Django 2.1.15 on 2025-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0140_auto_20250913_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposexamen',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
