# Generated by Django 2.1.15 on 2025-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0141_auto_20250913_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causasexterna',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='estadosinterconsulta',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposantecedente',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposfolio',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposincapacidad',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='viasegreso',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='viasingreso',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
