# Generated by Django 2.1.15 on 2025-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0142_auto_20250913_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposinterconsulta',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
