# Generated by Django 2.1.15 on 2025-09-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0144_auto_20250913_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='facturado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('N', 'Inactivo')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historiaresultados',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
