# Generated by Django 2.1.15 on 2025-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0145_auto_20250913_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='estadoReg',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='historia',
            name='antibioticos',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='inmovilizacion',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='interconsulta',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='irritacion',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='llenadoCapilar',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='monitoreo',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='movilidadLimitada',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='nauseas',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='neurologia',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='notaAclaratoria',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='pulsos',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='retiroPuntos',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='vomito',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
    ]
