# Generated by Django 2.1.15 on 2025-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0146_auto_20250915_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
