# Generated by Django 2.1.15 on 2025-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0148_auto_20250915_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='cita1Vez',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='citaControl',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='consentimientoInformado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='distribucionTerceros',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='finalidad',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='honorarios',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='manejaInterfaz',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='solicitaEnfermeria',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
