# Generated by Django 2.1.15 on 2025-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0151_auto_20250915_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='flagSivigila',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='historialincapacidades',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposdiagnostico',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
