# Generated by Django 2.1.15 on 2025-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0153_auto_20250915_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgos',
            name='abdomen',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='cara',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='columna',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='cuello',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='exaMdGeneral',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='factorTvp',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='fxCraneo',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='miembrosInferiores',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='miembrosSuperiores',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='nariz',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='neurologicos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='oidos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='ojos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='hallazgos',
            name='torax',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='nivelesclinica',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='revisionsistemas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tipostriage',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='turnosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
