# Generated by Django 2.1.15 on 2025-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0155_auto_20250915_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedci',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='frecuenciasaplicacion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='indicacionesespeciales',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='medicamentosdci',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='productosnutricion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposdispositivomedico',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposmedicamento',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposproductosnutricion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
