# Generated by Django 2.1.15 on 2025-09-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0157_auto_20250915_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='antibiotico',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='urgente',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='principiosactivos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
