# Generated by Django 2.1.15 on 2025-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0159_auto_20250915_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='rutaImagen',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaexamenes',
            name='rutaVideo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
