# Generated by Django 2.1.15 on 2025-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0160_auto_20250917_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='respuestaConsulta',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
