# Generated by Django 2.1.15 on 2025-09-17 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0161_auto_20250917_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinterconsultas',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
