# Generated by Django 2.1.15 on 2025-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0162_auto_20250917_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='nota',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
