# Generated by Django 2.1.15 on 2025-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0164_auto_20250917_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaexamenes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
