# Generated by Django 2.1.15 on 2025-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0165_auto_20250925_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
