# Generated by Django 2.1.15 on 2025-09-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0166_auto_20250926_0700'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examenes',
            name='examenesNombreIdx',
        ),
        migrations.AlterUniqueTogether(
            name='examenes',
            unique_together={('codigoCups',)},
        ),
    ]
