# Generated by Django 2.1.15 on 2025-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0167_auto_20250926_0720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examenes',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='examenes',
            index=models.Index(fields=['nombre'], name='examenesNombreIdx'),
        ),
    ]
