# Generated by Django 2.1.15 on 2025-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0168_auto_20250926_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooxigenacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
