# Generated by Django 2.1.15 on 2025-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0169_auto_20250929_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooxigenacion',
            name='flujoLtsAire',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tipooxigenacion',
            name='flujoLtsOxigeno',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
