# Generated by Django 2.1.15 on 2025-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0171_historialenfermedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaexamenes',
            name='resultado',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
