# Generated by Django 2.1.15 on 2025-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0172_historiaexamenes_resultado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historiaexamenes',
            index=models.Index(fields=['historia'], name='clinico_his_histori_f4c7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='historialantecedentes',
            index=models.Index(fields=['historia'], name='clinico_his_histori_961a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='historialdiagnosticos',
            index=models.Index(fields=['historia'], name='clinico_his_histori_22d2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialdietas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_01b799_idx'),
        ),
        migrations.AddIndex(
            model_name='historialenfermedades',
            index=models.Index(fields=['historia'], name='clinico_his_histori_d4219e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincapacidades',
            index=models.Index(fields=['historia'], name='clinico_his_histori_6a14c3_idx'),
        ),
        migrations.AddIndex(
            model_name='historialnotasenfermeria',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5c1023_idx'),
        ),
        migrations.AddIndex(
            model_name='historiamedicamentos',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5d8f52_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaoxigeno',
            index=models.Index(fields=['historia'], name='clinico_his_histori_9ec0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaresultados',
            index=models.Index(fields=['historiaExamenes'], name='clinico_his_histori_4fd783_idx'),
        ),
        migrations.AddIndex(
            model_name='historiarevisionsistemas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5127ef_idx'),
        ),
    ]
