# Generated by Django 2.1.15 on 2025-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0173_auto_20251002_0708'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialinterconsultas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_4e9271_idx'),
        ),
    ]
