# Generated by Django 2.1.15 on 2025-10-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0174_auto_20251002_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedicamentos',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut02', to='autorizaciones.AutorizacionesDetalle'),
        ),
    ]
