# Generated by Django 2.1.15 on 2025-10-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0072_ripsviasadministracion'),
        ('clinico', '0175_auto_20251009_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='viasadministracion',
            name='ripsViasAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsViasAdministracion'),
        ),
    ]
