# Generated by Django 2.1.15 on 2025-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0176_viasadministracion_ripsviasadministracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiamedicamentos',
            name='autorizacion',
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='autorizacion_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
