# Generated by Django 2.1.15 on 2025-11-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0025_tablamaterialsuturacuracion_tipohonorario'),
        ('clinico', '0177_auto_20251106_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario76091', to='tarifarios.TiposHonorarios'),
        ),
    ]
