# Generated by Django 2.1.15 on 2025-11-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0061_remove_cirugiasmaterialqx_cups'),
        ('planta', '0017_auto_20250924_1037'),
        ('clinico', '0178_examenes_tipohonorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugia_3221', to='cirugia.Cirugias')),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historia_3223', to='clinico.Historia')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.AddIndex(
            model_name='historialcirugias',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5721fb_idx'),
        ),
    ]
