# Generated by Django 2.1.15 on 2025-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0002_auto_20240916_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='fechaPrueba',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
