# Generated by Django 2.1.15 on 2025-02-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0058_auto_20241126_1550'),
        ('planta', '0005_planta_correo'),
        ('cartera', '0012_pagos_valorencurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosGlosas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlosasConceptoEspecifico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GlosasConceptoGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='glosas',
            old_name='fechaGlosa',
            new_name='fechaRecepcion',
        ),
        migrations.RenameField(
            model_name='glosas',
            old_name='observacones',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='glosas',
            old_name='totalGlosa',
            new_name='saldoFactura',
        ),
        migrations.RemoveField(
            model_name='glosas',
            name='detalladaParcial',
        ),
        migrations.RemoveField(
            model_name='glosas',
            name='detalladaTotal',
        ),
        migrations.RemoveField(
            model_name='glosas',
            name='numeroGlosa',
        ),
        migrations.RemoveField(
            model_name='motivosglosas',
            name='codigo',
        ),
        migrations.AddField(
            model_name='glosas',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion02', to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosas',
            name='tipoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.TiposGlosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRecepcion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion01', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRespuesta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuesta01', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='valorGlosa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoDeAplicacion',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoGlosa',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='glosas',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario987', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosasconceptoespecifico',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoGeneral'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGloas02', to='cartera.EstadosGlosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.EstadosGlosas'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoEspecifico',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoEspecifico'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoGeneral'),
        ),
    ]
