# Generated by Django 2.1.15 on 2025-02-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0012_auto_20250207_0853'),
        ('planta', '0005_planta_correo'),
        ('cartera', '0013_auto_20250207_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosasDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('valorServicio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorGlosa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalSoportado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalAceptado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones', models.CharField(blank=True, max_length=120, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('glosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Glosas')),
                ('motivoGlosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.MotivosGlosas')),
                ('ripsDetalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle')),
                ('usuarioRegistro', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario787', to='planta.Planta')),
            ],
        ),
    ]
