# Generated by Django 2.1.15 on 2025-02-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0015_auto_20250207_1036'),
        ('cartera', '0015_auto_20250207_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos10', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos11', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos12', to='rips.RipsTipos'),
        ),
    ]
