# Generated by Django 2.1.15 on 2025-02-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0015_auto_20250207_1036'),
        ('cartera', '0016_auto_20250207_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosas',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsEnvios'),
        ),
    ]
