# Generated by Django 2.1.15 on 2025-02-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0017_glosas_ripsenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosglosas',
            name='codigo',
        ),
    ]
