# Generated by Django 2.1.15 on 2025-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0018_remove_estadosglosas_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosasdetalle',
            name='itemRips',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
