# Generated by Django 2.1.15 on 2025-04-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0034_auto_20250402_0943'),
        ('cartera', '0019_glosasdetalle_itemrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
    ]
