# Generated by Django 2.1.15 on 2025-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0021_glosas_totalglosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosas',
            name='totalNotasCredito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
