# Generated by Django 2.1.15 on 2025-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('cartera', '0022_glosas_totalnotascredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm10', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm11', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm12', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm05', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm06', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm08', to='sitios.ServiciosAdministrativos'),
        ),
    ]
