# Generated by Django 2.1.15 on 2025-09-09 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0015_planta_escajero'),
        ('sitios', '0023_salas_tiposala'),
        ('cartera', '0023_auto_20250502_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('totalEfectivo', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('totalTarjetasDebito', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('totalTarjetasCredito', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('totalCheques', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm335', to='sitios.ServiciosAdministrativos')),
                ('usuarioEntrega', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7397', to='planta.Planta')),
                ('usuarioRecibe', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7597', to='planta.Planta')),
                ('usuarioRegistro', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7297', to='planta.Planta')),
                ('usuarioSuperviza', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7497', to='planta.Planta')),
            ],
        ),
    ]
