# Generated by Django 2.1.15 on 2025-09-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('cartera', '0024_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estadoCaja',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='caja',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7648', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7645', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7647', to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7397', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7597', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7297', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='usuarioSuperviza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7497', to='planta.Planta'),
        ),
    ]
