# Generated by Django 2.1.15 on 2025-09-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0025_auto_20250910_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='totalChequesEsperado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='totalEfectivoEsperado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='totalEsperado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='totalTarjetasCreditoEsperado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='totalTarjetasDebitoEsperado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
