# Generated by Django 2.1.15 on 2025-09-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0026_auto_20250910_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
