# Generated by Django 2.1.15 on 2025-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0027_auto_20250915_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosfacturas',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagosfacturas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='radicaciones',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
