# Generated by Django 2.1.15 on 2025-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0028_auto_20250915_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
    ]
