# Generated by Django 2.1.15 on 2025-09-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0029_remisiones_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='glosas',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='caja',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosasdetalle',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notasdebito',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagosfacturas',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='radicaciones',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
    ]
