# Generated by Django 2.1.15 on 2025-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0030_auto_20250915_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1, null=True),
        ),
    ]
