# Generated by Django 2.1.15 on 2025-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0032_auto_20250915_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosas',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosasdetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notasdebito',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagosfacturas',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='radicaciones',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
    ]
