# Generated by Django 2.1.15 on 2025-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0033_auto_20250915_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='anulado',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1, null=True),
        ),
    ]
