# Generated by Django 2.1.15 on 2025-09-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0034_auto_20250915_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Caja'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosas',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='glosasdetalle',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notasdebito',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pagosfacturas',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='radicaciones',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
    ]
