# Generated by Django 2.1.15 on 2025-10-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0035_auto_20250916_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaspagos',
            name='codigoRips',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
