# Generated by Django 2.1.15 on 2025-10-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0074_auto_20251023_0953'),
        ('cartera', '0036_formaspagos_codigorips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glosasdetalle',
            old_name='totalAceptado',
            new_name='valorAceptado',
        ),
        migrations.RenameField(
            model_name='glosasdetalle',
            old_name='totalSoportado',
            new_name='valorSoportado',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsDetalle',
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic01', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced01', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='valorNotasCredito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
