# Generated by Django 2.1.15 on 2025-10-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0074_auto_20251023_0953'),
        ('cartera', '0037_auto_20251024_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons01', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros01', to='rips.RipsOtrosServicios'),
        ),
    ]
