# Generated by Django 2.1.15 on 2025-10-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0038_auto_20251024_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosasdetalle',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic01', to='rips.RipsMedicamentos'),
        ),
    ]
