# Generated by Django 2.1.15 on 2025-10-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0039_auto_20251024_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosas',
            name='valorGlosa',
        ),
    ]
