# Generated by Django 2.1.15 on 2025-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0040_remove_glosas_valorglosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosas',
            name='totalNotasCreditoOtras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='glosas',
            name='totalNotasDebito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
