# Generated by Django 2.1.15 on 2025-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0041_auto_20251028_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosasdetalle',
            name='valorNotasCreditoOtras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='valorNotasDebito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
