# Generated by Django 2.1.15 on 2025-11-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0107_auto_20251118_0914'),
        ('planta', '0017_auto_20250924_1037'),
        ('cartera', '0043_auto_20251028_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasCreditoDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('valorNota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('E', 'Descuentos'), ('D', 'Devolucion'), ('E', 'Error')], default='D', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion103', to='facturacion.Facturacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='notascredito',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='notascredito',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='notascredito',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='notascredito',
            name='itemFactura',
        ),
        migrations.AlterField(
            model_name='glosasdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario743', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario799', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario796', to='planta.Planta'),
        ),
    ]
