# Generated by Django 2.1.15 on 2025-11-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0077_auto_20251118_0818'),
        ('cartera', '0044_auto_20251119_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposNotasCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notascredito',
            name='ripsId',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='itemFactura',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons0x1', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic0x1', to='rips.RipsMedicamentos'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros0x1', to='rips.RipsOtrosServicios'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced0x1', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='tiposNotasCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotaCre01', to='cartera.TiposNotasCredito'),
        ),
    ]
