# Generated by Django 2.1.15 on 2025-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0045_auto_20251120_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notascredito',
            name='codDian',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='codQr',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='cufeDef',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='cufeVr',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='estadoDian',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='mensajeDian',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='nomArchivo',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='prefijo',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaQr',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaRaiz',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaXml',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaXmlFirmado',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaXmlRespuesta',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='rutaZip',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='notascredito',
            name='trackId',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
