# Generated by Django 2.1.15 on 2025-11-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0077_auto_20251118_0818'),
        ('cartera', '0046_auto_20251120_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascredito',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsEnvios'),
        ),
    ]
