# Generated by Django 2.1.15 on 2025-11-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0078_ripsdetalle_notacredito'),
        ('planta', '0017_auto_20250924_1037'),
        ('cartera', '0047_notascredito_ripsenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasCreditoDetalleRips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorNota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='ripsConsultas',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='ripsMedicamentos',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='ripsOtrosServicios',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='ripsProcedimientos',
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='notaCreditoDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.NotasCreditoDetalle'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons0xy1', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic0xy1', to='rips.RipsMedicamentos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros0xy2', to='rips.RipsOtrosServicios'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced0xy1', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='tiposNotasCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotaCre02', to='cartera.TiposNotasCredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7956', to='planta.Planta'),
        ),
    ]
