# Generated by Django 2.1.15 on 2025-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0050_auto_20251121_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='valorrRegistrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
