# Generated by Django 2.1.15 on 2025-11-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0051_notascreditodetallerips_valorrregistrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notascreditodetallerips',
            old_name='valorrRegistrado',
            new_name='valorRegistrado',
        ),
    ]
