# Generated by Django 2.1.15 on 2025-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0052_auto_20251121_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='itemFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
