# Generated by Django 2.1.15 on 2025-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0053_notascreditodetallerips_itemfactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notascreditodetallerips',
            name='valorRegistrado',
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='valorRegistrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
