# Generated by Django 2.1.15 on 2025-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0054_auto_20251121_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notascreditodetalle',
            old_name='valorRegistrado',
            new_name='saldofactura',
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='totalFactura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='totalGlosas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='totalNotasCredito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
