# Generated by Django 2.1.15 on 2025-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0055_auto_20251124_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='valorNotasCreditoOtras',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='valorNotasDebito',
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='saldofactura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='totalFactura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
