# Generated by Django 2.1.15 on 2025-11-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0056_auto_20251124_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='saldofactura',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='totalFactura',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='saldofactura',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='totalFactura',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='totalGlosas',
        ),
        migrations.RemoveField(
            model_name='notascreditodetalle',
            name='totalNotasCredito',
        ),
    ]
