# Generated by Django 2.1.15 on 2025-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0109_auto_20251124_0844'),
        ('planta', '0017_auto_20250924_1037'),
        ('rips', '0079_auto_20251124_1508'),
        ('cartera', '0057_auto_20251124_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosasDetalleRips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('itemRips', models.IntegerField(blank=True, null=True)),
                ('ripsId', models.IntegerField(blank=True, null=True)),
                ('valorServicio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorGlosa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorSoportado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorAceptado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorNotasCredito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=120, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='itemFactura',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='itemRips',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsConsultas',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsId',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsMedicamentos',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsOtrosServicios',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsProcedimientos',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='ripsTipos',
        ),
        migrations.RemoveField(
            model_name='glosasdetalle',
            name='valorServicio',
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion10322', to='facturacion.Facturacion'),
        ),
        migrations.AlterField(
            model_name='glosasdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7423', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='glosasDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasDetalle'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons01', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic01', to='rips.RipsMedicamentos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros01', to='rips.RipsOtrosServicios'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced01', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos10', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario79533', to='planta.Planta'),
        ),
    ]
