# Generated by Django 2.1.15 on 2025-11-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0058_auto_20251126_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosas',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='glosas',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='glosas',
            name='saldoFactura',
        ),
    ]
