# Generated by Django 2.1.15 on 2025-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0004_auto_20241120_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
