# Generated by Django 2.1.15 on 2025-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0006_planta_serviciosadministrativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='documento',
            field=models.CharField(max_length=30),
        ),
    ]
