# Generated by Django 2.1.15 on 2025-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0007_auto_20250502_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='serviciosAdministrativos',
        ),
        migrations.AlterField(
            model_name='planta',
            name='documento',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
