# Generated by Django 2.1.15 on 2025-05-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('planta', '0008_auto_20250502_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm22', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='documento',
            field=models.CharField(max_length=30),
        ),
    ]
