# Generated by Django 2.1.15 on 2025-05-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0009_auto_20250502_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='serviciosAdministrativos',
        ),
    ]
