# Generated by Django 2.1.15 on 2025-09-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20250805_1540'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planta',
            unique_together={('tipoDoc', 'documento')},
        ),
    ]
