# Generated by Django 2.1.15 on 2025-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0012_auto_20250905_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planta',
            unique_together=set(),
        ),
    ]
