# Generated by Django 2.1.15 on 2025-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0014_auto_20250905_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='esCajero',
            field=models.CharField(blank=True, default='N', editable=False, max_length=1, null=True),
        ),
    ]
