# Generated by Django 2.1.15 on 2025-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0016_auto_20250915_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
