# Generated by Django 2.1.15 on 2025-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0013_auto_20241115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedesclinica',
            name='codigoHabilitacion',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
