# Generated by Django 2.1.15 on 2025-04-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
        ('sitios', '0014_sedesclinica_codigohabilitacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('tipoDoc', 'documento', 'consec')},
        ),
    ]
