# Generated by Django 2.1.15 on 2025-04-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
        ('sitios', '0015_auto_20250416_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('tipoDoc', 'documento', 'consec', 'disponibilidad')},
        ),
    ]
