# Generated by Django 2.1.15 on 2025-05-05 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('dependenciaTipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.DependenciasTipo')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosAdministrativos')),
                ('ubicaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Ubicaciones')),
            ],
        ),
    ]
