# Generated by Django 2.1.15 on 2025-05-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0012_auto_20250505_0902'),
        ('sitios', '0018_salas'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='estadoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosSalas'),
        ),
    ]
