# Generated by Django 2.1.15 on 2025-05-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0019_salas_estadosala'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosAdministrativos'),
        ),
    ]
