# Generated by Django 2.1.15 on 2025-05-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0020_dependencias_serviciosadministrativos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='ubicaciones',
        ),
    ]
