# Generated by Django 2.1.15 on 2025-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0021_remove_salas_ubicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
