# Generated by Django 2.1.15 on 2025-05-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0022_tipossalas'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='tipoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.TiposSalas'),
        ),
    ]
