# Generated by Django 2.1.15 on 2025-10-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0068_auto_20251017_0818'),
        ('sitios', '0024_auto_20250915_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='ripsMunicipios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsMunicipios'),
        ),
    ]
