# Generated by Django 2.1.15 on 2025-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0025_municipios_ripsmunicipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='finServicio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='salas',
            name='iniciaServicio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
