# Generated by Django 2.1.15 on 2025-11-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0179_auto_20251113_0759'),
        ('sitios', '0026_auto_20251028_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
    ]
