# Generated by Django 2.1.15 on 2025-11-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0027_dependencias_cups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencias',
            name='cups',
        ),
    ]
