# Generated by Django 2.1.15 on 2025-04-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0079_auto_20250414_1630'),
        ('triage', '0006_auto_20240919_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas'),
        ),
    ]
