# Generated by Django 2.1.15 on 2025-08-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_auto_20250819_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='tiposCotizante',
        ),
    ]
