# Generated by Django 2.1.15 on 2025-08-20 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_remove_triage_tiposcotizante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
