# Generated by Django 2.1.15 on 2025-08-20 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0011_auto_20250820_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 20, 11, 44, 49, 613629), null=True),
        ),
    ]
