# Generated by Django 2.1.15 on 2025-08-20 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0012_auto_20250820_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
