# Generated by Django 2.1.15 on 2025-08-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20250805_1540'),
        ('triage', '0013_auto_20250820_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triage',
            unique_together={('tipoDoc', 'documento', 'consec')},
        ),
    ]
