# Generated by Django 2.1.15 on 2025-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0015_auto_20250820_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='salidaDefinitiva',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
