# Generated by Django 2.1.15 on 2025-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0016_triage_salidadefinitiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='triage',
            name='salidaDefinitiva',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
