# Generated by Django 2.1.15 on 2025-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0017_auto_20250915_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='observaciones',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
