# Generated by Django 2.1.15 on 2025-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0041_auto_20250915_0949'),
        ('triage', '0018_auto_20250925_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
    ]
