# Generated by Django 2.1.15 on 2025-03-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0002_auto_20250331_1034'),
        ('contratacion', '0029_auto_20241031_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosprocedimientos',
            name='tarifariosDescripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion01', to='tarifarios.TarifariosDescripcion'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniosprocedimientos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='conveniossuministros',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='codigoHomologado',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='conveniossuministros',
            name='codigoHomologado',
        ),
        migrations.RemoveField(
            model_name='conveniossuministros',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='conveniossuministros',
            name='suministro',
        ),
        migrations.RemoveField(
            model_name='conveniossuministros',
            name='tipoTarifa',
        ),
        migrations.RemoveField(
            model_name='conveniossuministros',
            name='valor',
        ),
    ]
