# Generated by Django 2.1.15 on 2025-03-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_auto_20250331_1149'),
        ('contratacion', '0030_auto_20250331_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifa'),
        ),
    ]
