# Generated by Django 2.1.15 on 2025-03-31 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_auto_20250331_1149'),
        ('contratacion', '0031_convenios_tipotarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='tipoTarifa',
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0121', to='tarifarios.TarifariosDescripcion'),
        ),
    ]
