# Generated by Django 2.1.15 on 2025-03-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0032_auto_20250331_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='tarifariosDescripcion',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='ConveniosProcedimientos',
        ),
    ]
