# Generated by Django 2.1.15 on 2025-04-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_auto_20250331_1149'),
        ('contratacion', '0033_auto_20250331_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenios',
            old_name='tarifariosDescripcion',
            new_name='tarifariosDescripcionProc',
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionHono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0124', to='tarifarios.TarifariosDescripcion'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionSum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0123', to='tarifarios.TarifariosDescripcion'),
        ),
    ]
