# Generated by Django 2.1.15 on 2025-05-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0034_auto_20250402_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='vigenciaDesde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='vigenciaHasta',
            field=models.DateField(),
        ),
    ]
