# Generated by Django 2.1.15 on 2025-05-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0036_auto_20250502_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='tarifariosDescripcionHono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcionHonor0124', to='tarifarios.TarifariosDescripcionHonorarios'),
        ),
    ]
