# Generated by Django 2.1.15 on 2025-05-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0037_auto_20250515_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm315', to='sitios.ServiciosAdministrativos'),
        ),
    ]
