# Generated by Django 2.1.15 on 2025-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0038_auto_20250515_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='particular',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
