# Generated by Django 2.1.15 on 2025-01-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0009_ripscums_principiosactivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripstransaccion',
            name='numFactura',
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle03', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle09', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle07', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle06', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle04', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle08', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle01', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle05', to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='numDocumentoIdentificacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle02', to='rips.RipsDetalle'),
        ),
    ]
