# Generated by Django 2.1.15 on 2025-02-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0012_pagos_valorencurso'),
        ('rips', '0010_auto_20250129_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas02', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='itemFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa02', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas06', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='itemFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa06', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas07', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='itemFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa07', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas04', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='itemFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa04', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas05', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='itemFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa05', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
