# Generated by Django 2.1.15 on 2025-02-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0013_ripsenvios_sedesclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsTipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ripsdetalle',
            name='numeroFactura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
    ]
