# Generated by Django 2.1.15 on 2025-02-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0014_auto_20250207_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos01', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos04', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos06', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos07', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos02', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos05', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos03', to='rips.RipsTipos'),
        ),
    ]
