# Generated by Django 2.1.15 on 2025-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0016_auto_20250207_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripsdetalle',
            old_name='jsonAprobado',
            new_name='rutaJsonFactura',
        ),
        migrations.RenameField(
            model_name='ripsdetalle',
            old_name='jsonError',
            new_name='rutaJsonRespuesta',
        ),
        migrations.RemoveField(
            model_name='ripsenvios',
            name='jsonAprobado',
        ),
        migrations.RemoveField(
            model_name='ripsenvios',
            name='jsonError',
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='rutaPdf',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='rutaZip',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
