# Generated by Django 2.1.15 on 2025-02-13 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_planta_correo'),
        ('rips', '0017_auto_20250207_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='fechaGeneracionjson',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioEnvia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta145', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioGeneraJson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta146', to='planta.Planta'),
        ),
    ]
