# Generated by Django 2.1.15 on 2025-02-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0018_auto_20250213_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripstransaccion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle01', to='rips.RipsEnvios'),
        ),
    ]
