# Generated by Django 2.1.15 on 2025-02-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0019_auto_20250214_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripstransaccion',
            old_name='ripsDetalle',
            new_name='ripsEnvio',
        ),
    ]
