# Generated by Django 2.1.15 on 2025-02-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0013_auto_20241115_1218'),
        ('rips', '0020_auto_20250214_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripstransaccion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica769', to='sitios.SedesClinica'),
        ),
    ]
