# Generated by Django 2.1.15 on 2025-02-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0021_ripstransaccion_sedesclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripstransaccion',
            name='numDocumentoIdObligado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
