# Generated by Django 2.1.15 on 2025-02-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0022_auto_20250214_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsusuarios',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion12', to='rips.RipsTransaccion'),
        ),
    ]
