# Generated by Django 2.1.15 on 2025-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0023_ripsusuarios_ripstransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsenvios',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('Pendiente', 'Pendiente')], default='S', editable=False, max_length=1),
        ),
    ]
