# Generated by Django 2.1.15 on 2025-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0024_auto_20250214_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsdetalle',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('Rechazada', 'Rechazada')], default='S', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ripsenvios',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('Pendiente', 'Pendiente')], default='S', editable=False, max_length=10),
        ),
    ]
