# Generated by Django 2.1.15 on 2025-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0025_auto_20250217_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsTiposNotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTiposPagoModerador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('codigoAplicativo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ripsdetalle',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('Rechazada', 'Rechazada'), ('Sin respuesta', 'Sin Respuesta')], default='E', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ripsenvios',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('Pendiente', 'Pendiente')], default='P', editable=False, max_length=10),
        ),
    ]
