# Generated by Django 2.1.15 on 2025-02-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0026_auto_20250218_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripstransaccion',
            name='tipoNota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoNota01', to='rips.RipsTiposNotas'),
        ),
    ]
