# Generated by Django 2.1.15 on 2025-02-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0027_auto_20250218_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera01', to='rips.RipsTiposPagoModerador'),
        ),
    ]
