# Generated by Django 2.1.15 on 2025-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0028_ripsprocedimientos_tipopagomoderador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='valorPagoModerador',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
