# Generated by Django 2.1.15 on 2025-02-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0030_auto_20250218_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion13', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion17', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion19', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion20', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion14', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion18', to='rips.RipsTransaccion'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion15', to='rips.RipsTransaccion'),
        ),
    ]
