# Generated by Django 2.1.15 on 2025-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0031_auto_20250218_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='tipoRips',
            field=models.CharField(default='FACTURA', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ripsenvios',
            name='estadoPasoMinisterio',
            field=models.CharField(default='PENDIENTE', editable=False, max_length=10),
        ),
    ]
