# Generated by Django 2.1.15 on 2025-02-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0032_auto_20250219_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripstransaccion',
            name='numFactura',
            field=models.CharField(default='S', editable=False, max_length=20),
        ),
    ]
