# Generated by Django 2.1.15 on 2025-02-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0034_auto_20250220_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripsenvios',
            name='tipoRips',
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='tipoRipsNotas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipóNotas01', to='rips.RipsTiposNotas'),
        ),
    ]
