# Generated by Django 2.1.15 on 2025-02-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0035_auto_20250224_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripsenvios',
            old_name='tipoRipsNotas',
            new_name='ripsTiposNotas',
        ),
    ]
