# Generated by Django 2.1.15 on 2025-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0036_auto_20250224_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='concentracionMedicamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
