# Generated by Django 2.1.15 on 2025-03-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0039_auto_20250224_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsEstados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ripsenvios',
            name='estadoPasoMinisterio',
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='ripsEstados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsEtados01', to='rips.RipsEstados'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='ripsEstados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsEstados02', to='rips.RipsEstados'),
        ),
    ]
