# Generated by Django 2.1.15 on 2025-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0040_auto_20250304_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripshospitalizacion',
            name='tipoRips',
            field=models.CharField(blank=True, default='FACTURA', editable=False, max_length=10, null=True),
        ),
    ]
