# Generated by Django 2.1.15 on 2025-03-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0042_remove_ripsurgenciasobservacion_itemfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsreciennacido',
            name='numConsultasCPrenatal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
