# Generated by Django 2.1.15 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0043_auto_20250312_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsreciennacido',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
