# Generated by Django 2.1.15 on 2025-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0044_auto_20250312_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='rutaJson',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='rutaPdf',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='rutaZip',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
