# Generated by Django 2.1.15 on 2025-03-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0018_remove_estadosglosas_codigo'),
        ('rips', '0046_auto_20250312_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='GlosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas06', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadAceptada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadGlosada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='cantidadSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosa06', to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasCreditoGlosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasCreditoOtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='vAceptado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='valorGlosado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='valorSoportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
