# Generated by Django 2.1.15 on 2025-03-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0018_remove_estadosglosas_codigo'),
        ('rips', '0047_auto_20250314_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripsmedicamentos',
            old_name='GlosaId',
            new_name='glosa',
        ),
        migrations.RenameField(
            model_name='ripsprocedimientos',
            old_name='GlosaId',
            new_name='glosa',
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='glosaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas02', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='Glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas07', to='cartera.Glosas'),
        ),
    ]
