# Generated by Django 2.1.15 on 2025-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0049_auto_20250317_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsconsultas',
            name='vrServicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='vrServicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='vrServicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='vrServicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
