# Generated by Django 2.1.15 on 2025-03-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0050_auto_20250317_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripsconsultas',
            old_name='glosaId',
            new_name='glosa',
        ),
    ]
