# Generated by Django 2.1.15 on 2025-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0051_auto_20250318_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsconsultas',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsconsultas',
            name='itemFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripshospitalizacion',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='itemFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='itemFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='itemFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsreciennacido',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ripsurgenciasobservacion',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
