# Generated by Django 2.1.15 on 2025-03-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0052_auto_20250318_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripshospitalizacion',
            name='tipoRips',
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos04', to='rips.RipsTipos'),
        ),
    ]
