# Generated by Django 2.1.15 on 2025-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0053_auto_20250320_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsdetalle',
            name='numeroFactura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
