# Generated by Django 2.1.15 on 2025-03-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0019_glosasdetalle_itemrips'),
        ('rips', '0054_auto_20250320_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsdetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Glosas'),
        ),
        migrations.AlterField(
            model_name='ripsdetalle',
            name='numeroFactura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
    ]
