# Generated by Django 2.1.15 on 2025-03-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0055_auto_20250321_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripscums',
            name='ripsUnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidad12', to='rips.RipsUmm'),
        ),
    ]
