# Generated by Django 2.1.15 on 2025-03-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0056_ripscums_ripsunidadmedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripscums',
            name='ripsTipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipo11', to='rips.RipsTipoMedicamento'),
        ),
    ]
