# Generated by Django 2.1.15 on 2025-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0057_ripscums_ripstipomedicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='vrServicio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
