# Generated by Django 2.1.15 on 2025-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0058_auto_20250326_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='vrServicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
