# Generated by Django 2.1.15 on 2025-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0059_auto_20250326_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsconsultas',
            name='valorPagoModerador',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ripsconsultas',
            name='vrServicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='cantidadMedicamento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='diasTratamiento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='valorPagoModerador',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='vrServicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ripsmedicamentos',
            name='vrUnitMedicamento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='cantidadOS',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='valorPagoModerador',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='vrServicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='vrUnitOS',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ripsprocedimientos',
            name='valorPagoModerador',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
