# Generated by Django 2.1.15 on 2025-04-11 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0060_auto_20250331_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='fechaRadicacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
