# Generated by Django 2.1.15 on 2025-04-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_planta_correo'),
        ('rips', '0061_ripsenvios_fecharadicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta149', to='planta.Planta'),
        ),
    ]
