# Generated by Django 2.1.15 on 2025-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0063_ripsenvios_serviciosadministrativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='ripsconsultas',
            name='tipoDiagnosticoPrincipal',
            field=models.CharField(choices=[('UNO', 'Impresion Diagnostica'), ('DOS', 'Confirmado nuevo'), ('TRES', 'Confirmado repetido')], default='A', editable=False, max_length=21),
        ),
        migrations.AlterField(
            model_name='ripsdetalle',
            name='estadoPasoMinisterio',
            field=models.CharField(choices=[('E', 'Enviada'), ('R', 'Rechazada'), ('S', 'SinRespuesta')], default='E', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ripsdetalle',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='ripsenvios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codSexo',
            field=models.CharField(choices=[('H', 'Masculino'), ('M', 'Femenino'), ('I', 'Indeterminado')], default='A', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codZonaTerritorialResidencia',
            field=models.CharField(choices=[('UNO', 'Rural'), ('DOS', 'Urbano')], default='A', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='ripsusuarios',
            name='incapacidad',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='A', editable=False, max_length=2),
        ),
    ]
