# Generated by Django 2.1.15 on 2025-10-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0046_auto_20250915_0858'),
        ('rips', '0064_auto_20250915_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_03', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_06', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_09', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_10', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_04', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_07', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_05', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_02', to='admisiones.Ingresos'),
        ),
    ]
