# Generated by Django 2.1.15 on 2025-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0065_auto_20251009_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='respuesta',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='rutaRespuestaJson',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
