# Generated by Django 2.1.15 on 2025-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0067_ripsmunicipios_ripszonaterritorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsmunicipios',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
