# Generated by Django 2.1.15 on 2025-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0068_auto_20251017_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codZonaTerritorialResidencia',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
