# Generated by Django 2.1.15 on 2025-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0069_auto_20251017_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsusuarios',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
