# Generated by Django 2.1.15 on 2025-10-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0070_auto_20251017_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripscums',
            name='administracion',
        ),
        migrations.RemoveField(
            model_name='ripscums',
            name='principioActivo',
        ),
    ]
