# Generated by Django 2.1.15 on 2025-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0071_auto_20251020_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsViasAdministracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
