# Generated by Django 2.1.15 on 2025-10-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0072_ripsviasadministracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripscums',
            name='viaAdministracion',
        ),
        migrations.AddField(
            model_name='ripscums',
            name='ripsViasAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ViasAdmon10', to='rips.RipsViasAdministracion'),
        ),
    ]
