# Generated by Django 2.1.15 on 2025-10-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0073_auto_20251020_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsusuarios',
            name='codZonaTerritorialResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SonaRes01', to='rips.RipsZonaTerritorial'),
        ),
    ]
