# Generated by Django 2.1.15 on 2025-11-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0074_auto_20251023_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera012', to='rips.RipsTiposPagoModerador'),
        ),
    ]
