# Generated by Django 2.1.15 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0075_ripsotrosservicios_tipopagomoderador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='nomTecnologiaSalud',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
