# Generated by Django 2.1.15 on 2025-11-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0104_auto_20251118_0818'),
        ('rips', '0076_auto_20251113_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsCups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('descripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCups_01', to='facturacion.Conceptos')),
            ],
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='nomTecnologiaSaludCups',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='codTecnologiaSaludCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCups11', to='rips.RipsCups'),
        ),
    ]
