# Generated by Django 2.1.15 on 2025-11-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0047_notascredito_ripsenvio'),
        ('rips', '0077_auto_20251118_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsdetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.NotasCredito'),
        ),
    ]
