# Generated by Django 2.1.15 on 2025-11-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0057_auto_20251124_0805'),
        ('rips', '0078_ripsdetalle_notacredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='cantidadAceptada',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='cantidadGlosada',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='cantidadSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='vAceptado',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='valorGlosado',
        ),
        migrations.RemoveField(
            model_name='ripsconsultas',
            name='valorSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='cantidadAceptada',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='cantidadGlosada',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='cantidadSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='vAceptado',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='valorGlosado',
        ),
        migrations.RemoveField(
            model_name='ripsmedicamentos',
            name='valorSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='cantidadAceptada',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='cantidadGlosada',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='cantidadSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='vAceptado',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='valorGlosado',
        ),
        migrations.RemoveField(
            model_name='ripsotrosservicios',
            name='valorSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='cantidadAceptada',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='cantidadGlosada',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='cantidadSoportado',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='vAceptado',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='valorGlosado',
        ),
        migrations.RemoveField(
            model_name='ripsprocedimientos',
            name='valorSoportado',
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito0002', to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito00304', to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito00214', to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito0003', to='cartera.NotasCredito'),
        ),
    ]
