# Generated by Django 2.1.15 on 2025-02-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0017_glosas_ripsenvio'),
        ('rips', '0015_auto_20250207_1036'),
        ('facturacion', '0058_auto_20241126_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaciondetalle',
            old_name='cantidadAceptada',
            new_name='valorNotaDebito',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='cantidadGlosada',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='cantidadSoportado',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='fechaNotaCredito',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='motivoGlosa',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='numeroNotaCredito',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='numeroglosa',
        ),
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='observacionNotaCredito',
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups129', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaDebito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.NotasDebito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos108', to='rips.RipsTipos'),
        ),
    ]
