# Generated by Django 2.1.15 on 2025-02-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0003_auto_20240916_1100'),
        ('facturacion', '0060_auto_20250207_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaciondetalle',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut03', to='autorizaciones.Autorizaciones'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut05', to='autorizaciones.Autorizaciones'),
        ),
    ]
