# Generated by Django 2.1.15 on 2025-02-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0109_auto_20250224_0904'),
        ('facturacion', '0061_auto_20250224_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='autorizacion',
        ),
        migrations.RemoveField(
            model_name='liquidaciondetalle',
            name='autorizacion',
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed01', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='mipres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed02', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='mipres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
