# Generated by Django 2.1.15 on 2025-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0062_auto_20250224_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suministros',
            old_name='ripsUnidadMedica',
            new_name='ripsUnidadMedida',
        ),
    ]
