# Generated by Django 2.1.15 on 2025-02-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0034_auto_20250220_1632'),
        ('facturacion', '0063_auto_20250224_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministros',
            name='formasFarmaceutica',
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadUpr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidadUpr01', to='rips.RipsUnidadUpr'),
        ),
    ]
