# Generated by Django 2.1.15 on 2025-02-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0064_auto_20250224_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sum102', to='facturacion.Suministros'),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministros05', to='facturacion.Suministros'),
        ),
    ]
