# Generated by Django 2.1.15 on 2025-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0065_auto_20250225_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaciondetalle',
            name='mipres',
        ),
        migrations.RemoveField(
            model_name='liquidaciondetalle',
            name='mipres',
        ),
    ]
