# Generated by Django 2.1.15 on 2025-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0066_auto_20250225_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
