# Generated by Django 2.1.15 on 2025-02-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0014_sedesclinica_codigohabilitacion'),
        ('facturacion', '0067_suministros_requiereautorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica398', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica789', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica667', to='sitios.SedesClinica'),
        ),
    ]
