# Generated by Django 2.1.15 on 2025-02-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0068_auto_20250225_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidaciondetalle',
            old_name='codigoCups',
            new_name='examen',
        ),
    ]
