# Generated by Django 2.1.15 on 2025-02-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0069_auto_20250225_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaciondetalle',
            old_name='codigoCups',
            new_name='examen',
        ),
    ]
