# Generated by Django 2.1.15 on 2025-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0070_auto_20250226_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
