# Generated by Django 2.1.15 on 2025-02-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0071_auto_20250226_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministros',
            name='mipres',
        ),
    ]
