# Generated by Django 2.1.15 on 2025-03-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
        ('facturacion', '0072_remove_suministros_mipres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniospaciente',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='conveniospaciente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='conveniospaciente',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='conveniospaciente',
            name='usuarioRegistro',
        ),
        migrations.AlterField(
            model_name='conveniospacienteingresos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios0221', to='contratacion.Convenios'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniospacienteingresos',
            unique_together={('tipoDoc', 'documento', 'consecAdmision')},
        ),
        migrations.DeleteModel(
            name='ConveniosPaciente',
        ),
    ]
