# Generated by Django 2.1.15 on 2025-03-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_auto_20250331_1149'),
        ('facturacion', '0073_auto_20250331_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposTarifa0221', to='tarifarios.TiposTarifa'),
        ),
    ]
