# Generated by Django 2.1.15 on 2025-03-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0074_conveniospacienteingresos_tipostarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniospacienteingresos',
            name='tiposTarifa',
        ),
    ]
