# Generated by Django 2.1.15 on 2025-04-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
        ('contratacion', '0034_auto_20250402_0943'),
        ('facturacion', '0075_remove_conveniospacienteingresos_tipostarifa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniospacienteingresos',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
    ]
