# Generated by Django 2.1.15 on 2025-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0076_auto_20250408_1213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['nombre'], name='suministrosNombreIdx'),
        ),
    ]
