# Generated by Django 2.1.15 on 2025-04-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0034_auto_20250402_0943'),
        ('facturacion', '0077_auto_20250414_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacion',
            unique_together={('id', 'convenio')},
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('id', 'convenio')},
        ),
    ]
