# Generated by Django 2.1.15 on 2025-04-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
        ('contratacion', '0034_auto_20250402_0943'),
        ('facturacion', '0078_auto_20250414_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacion',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
    ]
