# Generated by Django 2.1.15 on 2025-04-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20250424_1453'),
        ('facturacion', '0079_auto_20250414_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('tipoDoc', 'documento', 'consecAdmision')},
        ),
    ]
