# Generated by Django 2.1.15 on 2025-04-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0080_auto_20250429_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together=set(),
        ),
    ]
