# Generated by Django 2.1.15 on 2025-04-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0081_auto_20250429_1208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacion',
            unique_together=set(),
        ),
    ]
