# Generated by Django 2.1.15 on 2025-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('facturacion', '0082_auto_20250429_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm20', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm21', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm51', to='sitios.ServiciosAdministrativos'),
        ),
    ]
