# Generated by Django 2.1.15 on 2025-05-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0083_auto_20250502_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciru0111', to='cirugia.Cirugias'),
        ),
    ]
