# Generated by Django 2.1.15 on 2025-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0086_auto_20250829_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='anticipos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='anticipos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
