# Generated by Django 2.1.15 on 2025-09-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0087_auto_20250829_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='notasCredito',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='notasCredito',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='notasDebito',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
