# Generated by Django 2.1.15 on 2025-09-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0088_auto_20250902_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
    ]
