# Generated by Django 2.1.15 on 2025-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0089_conveniospacienteingresos_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='conceptosafacturar',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='conveniospacienteingresos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='eapb',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='fosyga',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='particular',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='estadoEnvioDyan',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='reprocesarDian',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='tipoFacturaDyan',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='estadoRegistro',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='tipoRegistro',
            field=models.CharField(blank=True, choices=[('M', 'MANUAL'), ('S', 'SISTEMAS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='estadoRegistro',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacioncirugias',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='estadoRegistro',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='tipoRegistro',
            field=models.CharField(blank=True, choices=[('M', 'MANUAL'), ('S', 'SISTEMAS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refacturacion',
            name='estadoRegistro',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='regimenestipopago',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='salarioslegales',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='salariosminimoslegales',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='AnatoPos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='altoCosto',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='antibiotico',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='control',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='controlStock',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='enfermeria',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='facturable',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='genericoPos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='infusion',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='invAlmacen',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='invFarmacia',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='magistralControl',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='nutricion',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='oncologico',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='ortesis',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='pos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='regulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='requiereAutorizacion',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='sispro',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='terapia',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='vence',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tiposempresa',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tipossuministro',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
