# Generated by Django 2.1.15 on 2025-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0090_auto_20250915_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No'), ('R', 'Refacturada')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='estadoEnvioDyan',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No'), ('R', 'Refacturada')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='reprocesarDian',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No'), ('R', 'Refacturada')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='tipoFacturaDyan',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No'), ('R', 'Refacturada')], max_length=1, null=True),
        ),
    ]
