# Generated by Django 2.1.15 on 2025-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0091_auto_20250924_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
