# Generated by Django 2.1.15 on 2025-09-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0093_auto_20250926_0700'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='suministros',
            name='suministrosNombreIdx',
        ),
    ]
