# Generated by Django 2.1.15 on 2025-09-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0096_auto_20250926_0724'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['nombre'], name='suministrosNombreIdx'),
        ),
    ]
