# Generated by Django 2.1.15 on 2025-11-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0097_auto_20250926_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaciondetalle',
            name='codigoHomologado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='codigoHomologado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
