# Generated by Django 2.1.15 on 2025-11-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0098_auto_20251104_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario091', to='tarifarios.TiposHonorarios'),
        ),
    ]
