# Generated by Django 2.1.15 on 2025-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0099_auto_20251105_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='rutaJson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
