# Generated by Django 2.1.15 on 2025-11-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0100_facturacion_rutajson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario099', to='tarifarios.TiposHonorarios'),
        ),
    ]
