# Generated by Django 2.1.15 on 2025-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0101_auto_20251111_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaciondetalle',
            name='hojaDeGasto',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='hojaDeGasto',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
