# Generated by Django 2.1.15 on 2025-11-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0102_auto_20251111_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos1115', to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos0005', to='facturacion.Conceptos'),
        ),
    ]
