# Generated by Django 2.1.15 on 2025-11-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0179_auto_20251113_0759'),
        ('facturacion', '0103_auto_20251111_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptos',
            name='codAd',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='codAt',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAc',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAh',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAm',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAp',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAt',
        ),
        migrations.RemoveField(
            model_name='conceptos',
            name='ripsAu',
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tipoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tiposSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSuministro'),
        ),
    ]
