# Generated by Django 2.1.15 on 2025-11-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0106_estancias_cups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estancias',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='estancias',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='Estancias',
        ),
    ]
