# Generated by Django 2.1.15 on 2025-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0107_auto_20251118_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='saldofactura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
