# Generated by Django 2.1.15 on 2025-11-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0108_facturacion_saldofactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='saldofactura',
            new_name='saldoFactura',
        ),
    ]
