# Generated by Django 2.1.15 on 2025-02-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0022_auto_20250214_0841'),
        ('admisiones', '0035_auto_20250210_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='ripsTipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsTipousuario12', to='rips.RipsTipoUsuario'),
        ),
    ]
