# Generated by Django 2.1.15 on 2025-02-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0027_auto_20250218_0909'),
        ('admisiones', '0036_ingresos_ripstipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='ripsFinalidadConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsFinalidadConsulta'),
        ),
    ]
