# Generated by Django 2.1.15 on 2025-02-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0113_auto_20250225_0717'),
        ('admisiones', '0037_ingresos_ripsfinalidadconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id75', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxMuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id74', to='clinico.Diagnosticos'),
        ),
    ]
