# Generated by Django 2.1.15 on 2025-02-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0038_auto_20250225_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='dxMuerte',
        ),
    ]
