# Generated by Django 2.1.15 on 2025-03-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0018_auto_20250303_1251'),
        ('admisiones', '0039_remove_ingresos_dxmuerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='autorizaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizaciones.Autorizaciones'),
        ),
    ]
