# Generated by Django 2.1.15 on 2025-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0040_ingresos_autorizaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='ActaDefuncion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='ripsEdadGestacional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='ripsNumConsultasCPrenatal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='ripsPesoRecienNacido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='ripsRecienNacido',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
