# Generated by Django 2.1.15 on 2025-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('admisiones', '0041_auto_20250428_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm01', to='sitios.ServiciosAdministrativos'),
        ),
    ]
