# Generated by Django 2.1.15 on 2025-08-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0042_ingresos_serviciosadministrativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='serviciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id9', to='sitios.ServiciosSedes'),
        ),
    ]
