# Generated by Django 2.1.15 on 2025-08-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0043_auto_20250822_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='serviciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id10', to='sitios.ServiciosSedes'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='serviciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id11', to='sitios.ServiciosSedes'),
        ),
    ]
