# Generated by Django 2.1.15 on 2025-08-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0044_auto_20250822_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.EspecialidadesMedicos'),
        ),
    ]
