# Generated by Django 2.1.15 on 2025-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0045_auto_20250828_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furips',
            name='condicionAccidentado',
            field=models.CharField(blank=True, choices=[('A', 'Asegurado'), ('N', 'No_Asegurado'), ('V', 'Vehiculo_Fantasma'), ('P', 'Poliza_Falsa'), ('F', 'Vehiculo_en_fugao')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='furips',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='furips',
            name='tipoReferencia',
            field=models.CharField(blank=True, choices=[('R', 'Remision'), ('O', 'Orden de Servicio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='furips',
            name='tipoVehiculo',
            field=models.CharField(blank=True, choices=[('P', 'Servicio Particular'), ('U', 'Servicio Publico'), ('O', 'Servicio Oficial'), ('D', 'Poliza_Falsa'), ('T', 'Servicio Diplomatico'), ('R', 'De transporte Masivo'), ('E', 'Escolar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='muerte',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='remitido',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='ripsRecienNacido',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='salidaClinica',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
