# Generated by Django 2.1.15 on 2025-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0046_auto_20250915_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='incapacidad',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
    ]
