# Generated by Django 2.1.15 on 2025-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tiposdocumento_tipodocrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='documento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together={('tipoDoc', 'documento')},
        ),
    ]
