# Generated by Django 2.1.15 on 2025-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20250424_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='primerApellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='primerNombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
