# Generated by Django 2.1.15 on 2025-03-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0072_remove_suministros_mipres'),
        ('contratacion', '0029_auto_20241031_1016'),
        ('clinico', '0117_auto_20250325_1233'),
        ('planta', '0005_planta_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveniosProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Convenio124', to='contratacion.Convenios')),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosDescripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columna', models.CharField(blank=True, max_length=1, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('colValorBase', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor5', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor6', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor7', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor8', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor9', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor10', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups10121', to='clinico.Examenes')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto2271', to='facturacion.Conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='TiposHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario11', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa171', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas2020', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tarifariosdescripcion',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa11', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='conveniosprocedimientos',
            name='tarifariosDescripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion01', to='tarifarios.TarifariosDescripcion'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifariosprocedimientos',
            unique_together={('tiposTarifa', 'codigoCups', 'tipoHonorario')},
        ),
    ]
