# Generated by Django 2.1.15 on 2025-03-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0072_remove_suministros_mipres'),
        ('planta', '0005_planta_correo'),
        ('tarifarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifariosSuministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('colValorBase', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor5', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor6', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor7', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor8', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor9', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor10', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministro10121', to='facturacion.Suministros')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto22712', to='facturacion.Conceptos')),
                ('tiposTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa172', to='tarifarios.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas20202', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='TiposTarifaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='conveniosprocedimientos',
            name='tarifariosDescripcion',
        ),
        migrations.DeleteModel(
            name='ConveniosProcedimientos',
        ),
        migrations.AddField(
            model_name='tipostarifa',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa11', to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifariossuministros',
            unique_together={('tiposTarifa', 'codigoCum')},
        ),
    ]
