# Generated by Django 2.1.15 on 2025-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0003_auto_20250331_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifariosdescripcion',
            name='columna',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
