# Generated by Django 2.1.15 on 2025-03-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0117_auto_20250325_1233'),
        ('planta', '0005_planta_correo'),
        ('facturacion', '0072_remove_suministros_mipres'),
        ('tarifarios', '0005_auto_20250331_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifariosProcedimientosHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('colValorBase', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor5', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor6', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor7', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor8', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor9', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor10', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups101211', to='clinico.Examenes')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto22714', to='facturacion.Conceptos')),
                ('tipoHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario1122', to='tarifarios.TiposHonorarios')),
                ('tiposTarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa1711', to='tarifarios.TiposTarifa')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas20205', to='planta.Planta')),
            ],
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientos',
            name='tipoHonorario',
        ),
    ]
