# Generated by Django 2.1.15 on 2025-04-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_auto_20250331_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor1',
            new_name='valorHonorarioAnestesiologo',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor10',
            new_name='valorHonorarioAyudante',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor2',
            new_name='valorHonorarioCirujano',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor3',
            new_name='valorHonorarioDobleVia',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor4',
            new_name='valorHonorarioPerfucionista',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor5',
            new_name='valorHonorarioUnicaVia',
        ),
        migrations.RenameField(
            model_name='tarifariosprocedimientoshonorarios',
            old_name='colValor6',
            new_name='valorHonorarioViaAcceso',
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientoshonorarios',
            name='colValor7',
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientoshonorarios',
            name='colValor8',
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientoshonorarios',
            name='colValor9',
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientoshonorarios',
            name='colValorBase',
        ),
        migrations.RemoveField(
            model_name='tarifariosprocedimientoshonorarios',
            name='tipoHonorario',
        ),
    ]
