# Generated by Django 2.1.15 on 2025-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0007_auto_20250404_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifariosprocedimientos',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='tarifariosprocedimientos',
            index=models.Index(fields=['tiposTarifa', 'codigoCups'], name='tarifProcedTipostarifaIdx'),
        ),
    ]
