# Generated by Django 2.1.15 on 2025-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0008_auto_20250414_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifariossuministros',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='tarifariossuministros',
            index=models.Index(fields=['tiposTarifa', 'codigoCum'], name='tarifSuministTipostarifaIdx'),
        ),
    ]
