# Generated by Django 2.1.15 on 2025-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('tarifarios', '0009_auto_20250414_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifariosdescripcion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm30', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm31', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientoshonorarios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm33', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='tarifariossuministros',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm34', to='sitios.ServiciosAdministrativos'),
        ),
    ]
