# Generated by Django 2.1.15 on 2025-05-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0011_gruposqx_minimoslegalesqx_tablahonorarios_tablamaterialsuturacuracion_tablasalasdecirugia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MinimosLegalesQx',
            new_name='MinimosLegales',
        ),
    ]
