# Generated by Django 2.1.15 on 2025-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0013_auto_20250515_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablamaterialsuturacuracion',
            name='homologado',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tablasalasdecirugia',
            name='homologado',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
