# Generated by Django 2.1.15 on 2025-05-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('tarifarios', '0014_auto_20250515_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaHonorariosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('valorUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tiposHonorarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposHonorarios')),
                ('tiposTarifaProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.RenameModel(
            old_name='TablaHonorarios',
            new_name='TablaHonorariosSoat',
        ),
    ]
