# Generated by Django 2.1.15 on 2025-05-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0022_tipossalas'),
        ('tarifarios', '0017_tablasalasdecirugiaiss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='tiposSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.TiposSalas'),
        ),
    ]
