# Generated by Django 2.1.15 on 2025-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0019_tablamaterialsuturacuracioniss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposqx',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='minimoslegales',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablahonorariosiss',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablahonorariossoat',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablamaterialsuturacuracion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablamaterialsuturacuracioniss',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablasalasdecirugia',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tablasalasdecirugiaiss',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tarifariosdescripcion',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tarifariosdescripcionhonorarios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tarifariosprocedimientos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tarifariosprocedimientoshonorarios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tarifariossuministros',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposhonorarios',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tipostarifa',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tipostarifaproducto',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
