# Generated by Django 2.1.15 on 2025-11-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0020_auto_20250915_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario11222', to='tarifarios.TiposHonorarios'),
        ),
    ]
