# Generated by Django 2.1.15 on 2025-11-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0022_tablamaterialsuturacuracioniss_tipohonorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablamaterialsuturacuracion',
            name='minimosLegales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.MinimosLegales'),
        ),
    ]
