# Generated by Django 2.1.15 on 2025-11-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0023_tablamaterialsuturacuracion_minimoslegales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablasalasdecirugia',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario14452', to='tarifarios.TiposHonorarios'),
        ),
    ]
