# Generated by Django 2.1.15 on 2025-11-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0024_tablasalasdecirugia_tipohonorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablamaterialsuturacuracion',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario14754', to='tarifarios.TiposHonorarios'),
        ),
    ]
