# Generated by Django 2.1.15 on 2025-11-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0075_ripsotrosservicios_tipopagomoderador'),
        ('tarifarios', '0025_tablamaterialsuturacuracion_tipohonorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposhonorarios',
            name='ripsTipoOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipooTROsERV01', to='rips.RipsTipoOtrosServicios'),
        ),
    ]
