# Generated by Django 2.1.15 on 2025-11-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0179_auto_20251113_0759'),
        ('planta', '0017_auto_20250924_1037'),
        ('tarifarios', '0027_estanciasiss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=5, null=True)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('tipoEstancia', models.CharField(choices=[('S', 'SOAT'), ('I', 'ISS'), ('P', 'PARTICULAR')], default='I', editable=False, max_length=1)),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('cups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupsEstancias01', to='clinico.Examenes')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.RemoveField(
            model_name='estanciasiss',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='estanciasiss',
            name='usuarioRegistro',
        ),
        migrations.DeleteModel(
            name='EstanciasIss',
        ),
    ]
