# Generated by Django 2.1.15 on 2025-05-02 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0017_auto_20250502_0713'),
        ('facturacion', '0082_auto_20250429_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadEntrada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cantidadSalida', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valorEntrada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valorSalida', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('bodegas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Bodegas')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica')),
                ('suministros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('E', 'ENTRADA'), ('S', 'SALIDA')], max_length=20, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('bodegasEntrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bode01', to='sitios.Bodegas')),
                ('bodegasSalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bode02', to='sitios.Bodegas')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica')),
                ('suministros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
            ],
        ),
    ]
