# Generated by Django 2.1.15 on 2025-07-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('sitios', '0023_salas_tiposala'),
        ('enfermeria', '0011_signosenfermeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosenfermeria',
            name='enfermeraTurno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serenf01', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AlterField(
            model_name='aplicacionmedicamentos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf02', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='cuidadosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf03', to='planta.Planta'),
        ),
        migrations.AlterField(
            model_name='turnosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf01', to='planta.Planta'),
        ),
    ]
