# Generated by Django 2.1.15 on 2025-07-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0014_enfermeria_enfermeriadetalle_enfermeriaplaneacion_enfermeriarecibe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaexamenes',
            name='historiaMedicamentos',
        ),
        migrations.DeleteModel(
            name='HistoriaExamenes',
        ),
    ]
