# Generated by Django 2.1.15 on 2025-07-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0123_auto_20250519_1153'),
        ('enfermeria', '0015_auto_20250703_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasliquidosenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='notasliquidosenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='notasliquidosenfermeria',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='notasliquidosenfermeria',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='balanceliquidosenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='balanceliquidosenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='balanceliquidosenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='balanceliquidosenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='notasenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='notasenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='notasenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='notasenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='signosenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='signosenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='signosenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='signosenfermeria',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaBalanceLiquidosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaNotasEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaSignosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.DeleteModel(
            name='NotasLiquidosEnfermeria',
        ),
    ]
