# Generated by Django 2.1.15 on 2025-07-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0123_auto_20250519_1153'),
        ('enfermeria', '0016_auto_20250703_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionmedicamentos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='aplicacionmedicamentos',
            name='suministro',
        ),
        migrations.RemoveField(
            model_name='aplicacionmedicamentos',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='aplicacionmedicamentos',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='cuidadosenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='cuidadosenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cuidadosenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='cuidadosenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='dolorenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='dolorenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='dolorenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='dolorenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='heridasenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='heridasenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='heridasenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='heridasenfermeria',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='posicionpacientesenfermeria',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='posicionpacientesenfermeria',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='posicionpacientesenfermeria',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='posicionpacientesenfermeria',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaCuidadosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaDolorEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaHeridasEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaPosicionEnfermeria01', to='clinico.Historia'),
        ),
        migrations.DeleteModel(
            name='AplicacionMedicamentos',
        ),
    ]
