# Generated by Django 2.1.15 on 2025-07-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('enfermeria', '0017_auto_20250703_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermeriaTipoMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='F', editable=False, max_length=50, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3469', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermeriaTipoOrigen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='F', editable=False, max_length=50, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3467', to='planta.Planta')),
            ],
        ),
    ]
