# Generated by Django 2.1.15 on 2025-07-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0018_enfermeriatipomovimiento_enfermeriatipoorigen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeria',
            name='tipoOrden',
        ),
        migrations.RemoveField(
            model_name='enfermeriatipoorigen',
            name='fechaRegistro',
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='tipoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria01', to='enfermeria.EnfermeriaTipoOrigen'),
        ),
        migrations.AlterField(
            model_name='enfermeria',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria02', to='enfermeria.EnfermeriaTipoMovimiento'),
        ),
        migrations.AlterField(
            model_name='enfermeriatipomovimiento',
            name='nombre',
            field=models.CharField(blank=True, default='F', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriatipoorigen',
            name='nombre',
            field=models.CharField(default='F', max_length=50),
        ),
    ]
