# Generated by Django 2.1.15 on 2025-07-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_farmaciadespachosdispensa_item'),
        ('enfermeria', '0019_auto_20250714_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriarecibe',
            name='despacho',
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='despachosDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDispensa01', to='farmacia.FarmaciaDespachos'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='item',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
