# Generated by Django 2.1.15 on 2025-07-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0020_auto_20250714_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermeriaplaneacion',
            old_name='consecutivo',
            new_name='consecutivoPlaneacion',
        ),
        migrations.RemoveField(
            model_name='enfermeriaplaneacion',
            name='enfermeriaDetalle',
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeriaRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaRecibe1102', to='enfermeria.EnfermeriaRecibe'),
        ),
    ]
