# Generated by Django 2.1.15 on 2025-07-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('enfermeria', '0021_auto_20250714_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica384', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica378', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica379', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica386', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica380', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica383', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica381', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica385', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica377', to='sitios.SedesClinica'),
        ),
    ]
