# Generated by Django 2.1.15 on 2025-07-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0022_auto_20250714_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermeriarecibe',
            old_name='despachosDispensa',
            new_name='despachos',
        ),
        migrations.RemoveField(
            model_name='enfermeriarecibe',
            name='diasTratamiento',
        ),
        migrations.RemoveField(
            model_name='enfermeriarecibe',
            name='frecuencia',
        ),
    ]
