# Generated by Django 2.1.15 on 2025-07-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_auto_20250716_1221'),
        ('enfermeria', '0023_auto_20250716_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriadetalle',
            name='diasTratamiento',
        ),
        migrations.RemoveField(
            model_name='enfermeriadetalle',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDetalle', to='farmacia.FarmaciaDetalle'),
        ),
    ]
