# Generated by Django 2.1.15 on 2025-07-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_auto_20250717_0727'),
        ('enfermeria', '0024_auto_20250716_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDetalle02', to='farmacia.FarmaciaDetalle'),
        ),
    ]
