# Generated by Django 2.1.15 on 2025-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0025_enfermeriarecibe_farmaciadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriarecibe',
            name='item',
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='consecutivoMedicamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
