# Generated by Django 2.1.15 on 2025-07-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0026_auto_20250717_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriarecibe',
            name='consecutivoMedicamento',
        ),
    ]
