# Generated by Django 2.1.15 on 2025-07-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('enfermeria', '0027_remove_enfermeriarecibe_consecutivomedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposTurnosEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(default='A', max_length=50)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_377', to='sitios.SedesClinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf01', to='planta.Planta')),
            ],
        ),
        migrations.RemoveField(
            model_name='turnosenfermeria',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='turnosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_398', to='sitios.SedesClinica'),
        ),
        migrations.AlterField(
            model_name='turnosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf02', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='tiposTurnosEnfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposTurno01', to='enfermeria.TiposTurnosEnfermeria'),
        ),
    ]
