# Generated by Django 2.1.15 on 2025-07-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0042_ingresos_serviciosadministrativos'),
        ('enfermeria', '0028_auto_20250718_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeria',
            name='ingresoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ingreso987', to='admisiones.Ingresos'),
        ),
    ]
