# Generated by Django 2.1.15 on 2025-07-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0029_enfermeria_ingresopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.Enfermeria'),
        ),
    ]
