# Generated by Django 2.1.15 on 2025-07-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0030_enfermeriaplaneacion_enfermeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriaplaneacion',
            name='turnoEnfermeria',
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='turnoEnfermeriaAplica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaTipoTurno11013', to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='turnoEnfermeriaPlanea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaTipoTurno11012', to='enfermeria.TurnosEnfermeria'),
        ),
    ]
