# Generated by Django 2.1.15 on 2025-07-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0031_auto_20250723_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermeriaplaneacion',
            old_name='desdeFecha',
            new_name='fechaAplica',
        ),
        migrations.RenameField(
            model_name='enfermeriaplaneacion',
            old_name='hastaFecha',
            new_name='fechaPlanea',
        ),
    ]
