# Generated by Django 2.1.15 on 2025-07-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0125_historiamedicamentos_consecutivomedicamento'),
        ('enfermeria', '0032_auto_20250723_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='diasTratamiento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion'),
        ),
    ]
