# Generated by Django 2.1.15 on 2025-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0033_auto_20250723_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='cantidadDevuelta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='netoCantidad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
