# Generated by Django 2.1.15 on 2025-07-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_auto_20250725_1048'),
        ('enfermeria', '0034_auto_20250725_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermeriaDevolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermeriaDevolucionDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadDevuelta', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='farmaciaDespachosDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDespachosDispensa0222', to='farmacia.FarmaciaDespachosDispensa'),
        ),
    ]
