# Generated by Django 2.1.15 on 2025-07-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_auto_20250725_1135'),
        ('enfermeria', '0035_auto_20250725_1135'),
        ('sitios', '0023_salas_tiposala'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaDevolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaDevolucion061', to='farmacia.FarmaciaDevolucion'),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos261201', to='enfermeria.EnfermeriaRecibe'),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermeria3453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica3Enf9022', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='serviciosAdministrativosDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servDevuelve3231', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servRecibe32431', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaDevuelve4353', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaRecibe4553', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermeriaia3453', to='planta.Planta'),
        ),
    ]
