# Generated by Django 2.1.15 on 2025-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0036_auto_20250725_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriadevolucion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
