# Generated by Django 2.1.15 on 2025-07-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0037_auto_20250728_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaRecibe',
        ),
        migrations.AlterField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaDevolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos261201', to='enfermeria.EnfermeriaRecibe'),
        ),
    ]
