# Generated by Django 2.1.15 on 2025-07-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0039_auto_20250728_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaRecibe201', to='enfermeria.EnfermeriaRecibe'),
        ),
    ]
