# Generated by Django 2.1.15 on 2025-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0040_enfermeriadevoluciondetalle_enfermeriarecibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='anulado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='balanceliquidosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='cuidadosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='dolorenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='enfermeria',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriadetalle',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriadevolucion',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriadevoluciondetalle',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriaplaneacion',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriarecibe',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriatipomovimiento',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeriatipoorigen',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='heridasenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='notasenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='posicionpacientesenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='signosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tipobalanceliquidosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiposturnosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='turnosenfermeria',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1),
        ),
    ]
