# Generated by Django 2.1.15 on 2025-09-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0041_auto_20250915_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeria',
            name='ingresoPaciente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
