# Generated by Django 2.1.15 on 2025-02-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0065_auto_20250225_0717'),
        ('clinico', '0113_auto_20250225_0717'),
        ('autorizaciones', '0003_auto_20240916_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacionescups',
            name='codigoCups',
        ),
        migrations.AddField(
            model_name='autorizacionescups',
            name='clinicoExamenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examen809', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='autorizacionescups',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminist304', to='facturacion.Suministros'),
        ),
    ]
