# Generated by Django 2.1.15 on 2025-02-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0114_auto_20250225_0748'),
        ('autorizaciones', '0005_auto_20250225_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizaciones',
            old_name='numeroSoclicitud',
            new_name='numeroSolicitud',
        ),
        migrations.RenameField(
            model_name='autorizaciones',
            old_name='plantaSolicita',
            new_name='plantaOrdena',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='consec',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='dxPrinc',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='dxRel1',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='dxRel2',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='hClinica',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='medicoAutoriza',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='plantaAutoriza',
        ),
        migrations.RemoveField(
            model_name='autorizaciones',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Historia476', to='clinico.Historia'),
        ),
        migrations.AlterField(
            model_name='autorizaciones',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa765', to='facturacion.Empresas'),
        ),
    ]
