# Generated by Django 2.1.15 on 2025-02-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0006_auto_20250225_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='consec',
        ),
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='hClinica',
        ),
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='sedesClinica',
        ),
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='tipoDoc',
        ),
    ]
