# Generated by Django 2.1.15 on 2025-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0007_auto_20250225_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacionesdetalle',
            old_name='autorizacionesId',
            new_name='autorizaciones',
        ),
    ]
