# Generated by Django 2.1.15 on 2025-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0008_auto_20250225_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='numeroSolicitud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
