# Generated by Django 2.1.15 on 2025-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0009_auto_20250225_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='valorAutorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='valorSolicitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='cantidadAutorizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='cantidadSolicitada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
