# Generated by Django 2.1.15 on 2025-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0010_auto_20250227_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacionesdetalle',
            old_name='clinicoExamenes',
            new_name='examenes',
        ),
    ]
