# Generated by Django 2.1.15 on 2025-02-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0116_auto_20250226_0807'),
        ('autorizaciones', '0011_auto_20250227_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
    ]
