# Generated by Django 2.1.15 on 2025-02-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0072_remove_suministros_mipres'),
        ('autorizaciones', '0012_autorizacionesdetalle_tiposexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tipoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSuministro'),
        ),
    ]
