# Generated by Django 2.1.15 on 2025-02-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0014_estadosautorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacionesdetalle',
            name='autorizado',
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estAut02', to='autorizaciones.EstadosAutorizacion'),
        ),
        migrations.AlterField(
            model_name='autorizaciones',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoAut01', to='autorizaciones.EstadosAutorizacion'),
        ),
    ]
