# Generated by Django 2.1.15 on 2025-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0015_auto_20250228_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='numeroAutorizacion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
