# Generated by Django 2.1.15 on 2025-02-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0016_autorizacionesdetalle_numeroautorizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='examenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examen829', to='clinico.Examenes'),
        ),
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='tiposExamen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
    ]
