# Generated by Django 2.1.15 on 2025-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0017_auto_20250228_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='valorAutorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacionesdetalle',
            name='valorSolicitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
