# Generated by Django 2.1.15 on 2025-04-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0018_auto_20250303_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='plantaOrdena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
