# Generated by Django 2.1.15 on 2025-09-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0039_convenios_particular'),
        ('autorizaciones', '0020_autorizaciones_serviciosadministrativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios02271', to='contratacion.Convenios'),
        ),
    ]
