# Generated by Django 2.1.15 on 2025-09-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0129_historia_ordendecontrol'),
        ('autorizaciones', '0021_autorizaciones_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutMed01', to='clinico.HistoriaMedicamentos'),
        ),
    ]
