# Generated by Django 2.1.15 on 2025-09-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0024_auto_20250909_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizaciones',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizaciones.EstadosAutorizacion'),
        ),
    ]
