# Generated by Django 2.1.15 on 2025-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0026_auto_20250915_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='autorizadoPor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
