# Generated by Django 2.1.15 on 2025-05-05 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0010_auto_20250502_0901'),
        ('clinico', '0121_auto_20250502_1619'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('cirugia', '0007_gravedadcirugia_zonascirugia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirugiasParticipantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalidad', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CirugiasProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalidad', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='cirugias',
            old_name='horaQx',
            new_name='horaQxFinal',
        ),
        migrations.RenameField(
            model_name='cirugias',
            old_name='tipofractura',
            new_name='tipofactura',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='anestesiologo',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='ayudante1',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='ayudante2',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='circulante',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cirujano1',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cirujano2',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cirujano3',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups1',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups10',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups11',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups12',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups13',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups14',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups15',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups2',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups3',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups4',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups5',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups6',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups7',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups8',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='cups9',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='fechaQx',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad1',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad10',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad11',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad12',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad13',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad14',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad15',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad2',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad3',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad4',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad5',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad6',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad7',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad8',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='finalidad9',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='instrumentador',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='tiempoQx',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='tiempoQxProg',
        ),
        migrations.AddField(
            model_name='cirugias',
            name='fechaQxFinal',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='fechaQxInicial',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='horaQxInicial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaProg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias12', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups102', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta67', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias13', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='tipoHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario12', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta68', to='planta.Planta'),
        ),
    ]
