# Generated by Django 2.1.15 on 2025-05-05 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0018_salas'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('cirugia', '0008_auto_20250505_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HojaDeGasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='programacioncirugias',
            old_name='hora_programacion',
            new_name='horaProgramacionFin',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='fecha_programacion',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='serviciosSedes_id',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='subServiciosSedes_id',
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='fechaProgramacionFin',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='fechaProgramacionInicia',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='horaProgramacionInicia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Salas'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaFinAnestesia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaIniAnestesia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='estadoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosSalas'),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='hojadegasto',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias17', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='hojadegasto',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
