# Generated by Django 2.1.15 on 2025-05-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('clinico', '0121_auto_20250502_1619'),
        ('cirugia', '0009_auto_20250505_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HojaDeGasto',
            new_name='HojasDeGastos',
        ),
        migrations.RemoveField(
            model_name='recordanestesico',
            name='consecAdmision',
        ),
        migrations.RemoveField(
            model_name='recordanestesico',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='recordanestesico',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='cups10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups89', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='cups7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups86', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='cups8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups87', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='cups9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups88', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='recordanestesico',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.Cirugias'),
        ),
    ]
