# Generated by Django 2.1.15 on 2025-05-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0010_auto_20250505_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria54', to='autorizaciones.Autorizaciones'),
        ),
    ]
