# Generated by Django 2.1.15 on 2025-05-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0011_auto_20250505_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosProgramacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='estadoSala',
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosProgramacion'),
        ),
    ]
