# Generated by Django 2.1.15 on 2025-05-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0012_auto_20250505_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugiasparticipantes',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final005', to='cirugia.FinalidadCirugia'),
        ),
        migrations.AlterField(
            model_name='cirugiasprocedimientos',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final004', to='cirugia.FinalidadCirugia'),
        ),
    ]
