# Generated by Django 2.1.15 on 2025-05-06 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0020_dependencias_serviciosadministrativos'),
        ('facturacion', '0083_auto_20250502_0901'),
        ('cirugia', '0014_auto_20250505_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='timepoMaxQx',
            new_name='tiempoMaxQx',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='serviciosSedes_id',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='subServiciosSedes_id',
        ),
        migrations.AddField(
            model_name='cirugias',
            name='folioEvolucionPostQx',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='folioEvolucionPreQx',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='horaIngresoQuirofano',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='horaIngresoRecuperacion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='horaSalidaQuirofano',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='horaSalidaRecuperacion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='ingresoQuirofano',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='ingresoRecuperacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='salidaQuirofano',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='salidaRecuperacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm126', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx555', to='clinico.Diagnosticos'),
        ),
    ]
