# Generated by Django 2.1.15 on 2025-05-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0015_auto_20250506_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups1',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups10',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups2',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups3',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups4',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups5',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups6',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups7',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups8',
        ),
        migrations.RemoveField(
            model_name='programacioncirugias',
            name='cups9',
        ),
    ]
