# Generated by Django 2.1.15 on 2025-05-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0016_auto_20250506_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='fechaSolicia',
            new_name='fechaSolicita',
        ),
    ]
