# Generated by Django 2.1.15 on 2025-05-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0017_auto_20250506_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='sedesClinica_id',
            new_name='sedesClinica',
        ),
    ]
