# Generated by Django 2.1.15 on 2025-05-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0018_auto_20250506_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='solicitaSangree',
            new_name='solicitaSangre',
        ),
    ]
