# Generated by Django 2.1.15 on 2025-05-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0019_auto_20250506_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosProgramacion'),
        ),
    ]
