# Generated by Django 2.1.15 on 2025-05-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0021_tiposcirugia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='tiposCirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.TiposCirugia'),
        ),
    ]
