# Generated by Django 2.1.15 on 2025-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0023_cirugiasparticipantes_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='solicitaTiempoQx',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
