# Generated by Django 2.1.15 on 2025-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0024_auto_20250507_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='cantidadSangre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
