# Generated by Django 2.1.15 on 2025-05-07 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0025_auto_20250507_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='fechaProg',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
