# Generated by Django 2.1.15 on 2025-05-07 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0026_auto_20250507_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='fechaCancela',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaFinAnestesia',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaIniAnestesia',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaQxFinal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaQxInicial',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='fechaReprograma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='salidaRecuperacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
