# Generated by Django 2.1.15 on 2025-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0027_auto_20250507_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='estadoSalida',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
    ]
