# Generated by Django 2.1.15 on 2025-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0028_auto_20250507_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='fechaPrograma',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
