# Generated by Django 2.1.15 on 2025-05-07 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0029_auto_20250507_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='ingresoQuirofano',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='salidaQuirofano',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
