# Generated by Django 2.1.15 on 2025-05-08 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0032_auto_20250507_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacioncirugias',
            name='fechaProgramacionFin',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
