# Generated by Django 2.1.15 on 2025-05-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0033_auto_20250508_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacioncirugias',
            name='fechaProgramacionInicia',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
