# Generated by Django 2.1.15 on 2025-05-08 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0034_auto_20250508_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacioncirugias',
            name='fechaProgramacionFin',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='programacioncirugias',
            name='fechaProgramacionInicia',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
