# Generated by Django 2.1.15 on 2025-05-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0121_auto_20250502_1619'),
        ('cirugia', '0035_auto_20250508_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugias',
            name='dxRel2',
        ),
        migrations.RemoveField(
            model_name='cirugias',
            name='dxRel3',
        ),
        migrations.AddField(
            model_name='cirugias',
            name='analisis',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='impresionDx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx541', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='planx',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='dxPostQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx521', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='dxPreQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx511', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='dxPrinc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx531', to='clinico.Diagnosticos'),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='dxRel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx542', to='clinico.Diagnosticos'),
        ),
    ]
