# Generated by Django 2.1.15 on 2025-05-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0036_auto_20250513_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='tipofactura',
            new_name='tipofractura',
        ),
    ]
