# Generated by Django 2.1.15 on 2025-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0038_auto_20250513_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='HoraIniAnestesia',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaFinAnestesia',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaIngresoQuirofano',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaIngresoRecuperacion',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaQxFinal',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaQxInicial',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaSalidaQuirofano',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cirugias',
            name='horaSalidaRecuperacion',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
