# Generated by Django 2.1.15 on 2025-05-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0021_remove_salas_ubicaciones'),
        ('cirugia', '0039_auto_20250513_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Salas'),
        ),
    ]
