# Generated by Django 2.1.15 on 2025-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0041_cirugias_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='facturable',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='valorLiquidacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='viaAcceso',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cruento',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='incruento',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='regionOperatoria',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
