# Generated by Django 2.1.15 on 2025-05-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0042_auto_20250515_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionesOperatorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('organos', models.CharField(blank=True, max_length=250, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='cirugiasprocedimientos',
            name='regionOperatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.RegionesOperatorias'),
        ),
    ]
