# Generated by Django 2.1.15 on 2025-05-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0043_auto_20250515_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViasDeAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='viasDeAcceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.ViasDeAcceso'),
        ),
    ]
