# Generated by Django 2.1.15 on 2025-05-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0044_auto_20250515_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugiasparticipantes',
            name='viaAcceso',
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='viasDeAcceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceso104', to='cirugia.ViasDeAcceso'),
        ),
    ]
