# Generated by Django 2.1.15 on 2025-05-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0045_auto_20250515_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugiasmaterialqx',
            name='facturable',
        ),
    ]
