# Generated by Django 2.1.15 on 2025-05-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0122_auto_20250515_1127'),
        ('cirugia', '0046_remove_cirugiasmaterialqx_facturable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugiasparticipantes',
            name='viasDeAcceso',
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups1024', to='clinico.Examenes'),
        ),
    ]
