# Generated by Django 2.1.15 on 2025-05-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('cirugia', '0047_auto_20250516_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm129', to='sitios.ServiciosAdministrativos'),
        ),
    ]
