# Generated by Django 2.1.15 on 2025-10-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0051_auto_20250917_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
    ]
