# Generated by Django 2.1.15 on 2025-10-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0097_auto_20250926_0826'),
        ('cirugia', '0052_auto_20251028_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.ConveniosPacienteIngresos'),
        ),
    ]
