# Generated by Django 2.1.15 on 2025-10-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0053_cirugias_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
    ]
