# Generated by Django 2.1.15 on 2025-10-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0054_auto_20251029_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.CirugiasProcedimientos'),
        ),
    ]
