# Generated by Django 2.1.15 on 2025-10-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0055_cirugiasmaterialqx_cirugiaprocedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugiasparticipantes',
            name='cups',
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CiruProc10', to='cirugia.CirugiasProcedimientos'),
        ),
    ]
