# Generated by Django 2.1.15 on 2025-10-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0056_auto_20251031_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncirugias',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cir212', to='cirugia.Cirugias'),
        ),
    ]
