# Generated by Django 2.1.15 on 2025-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0057_programacioncirugias_cirugia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='unitario',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cirugiasmaterialqx',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
