# Generated by Django 2.1.15 on 2025-11-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0177_auto_20251106_1453'),
        ('cirugia', '0058_auto_20251031_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups1544', to='clinico.Examenes'),
        ),
    ]
