# Generated by Django 2.1.15 on 2025-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0059_cirugiasmaterialqx_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='hojaDeGasto',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
