# Generated by Django 2.1.15 on 2025-11-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0060_cirugiasmaterialqx_hojadegasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugiasmaterialqx',
            name='cups',
        ),
    ]
