# Generated by Django 2.1.15 on 2025-07-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('clinico', '0123_auto_20250519_1153'),
        ('facturacion', '0085_auto_20250519_1543'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despachos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoOrden', models.CharField(blank=True, default='C', editable=False, max_length=1, null=True)),
                ('tipoMovimiento', models.CharField(blank=True, default='F', editable=False, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaFarmacia01', to='clinico.Historia')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='sitios.ServiciosAdministrativos')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3450', to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosisCantidad', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cantidadOrdenada', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('diasTratamiento', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('dosisUnidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis')),
                ('farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmacia01', to='farmacia.Farmacia')),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion')),
                ('historiaMedicamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='clinico.HistoriaMedicamentos')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3451', to='planta.Planta')),
                ('viaAdministracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion')),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDispensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosisCantidad', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cantidadOrdenada', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('diasTratamiento', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos01', to='farmacia.Despachos')),
                ('dosisUnidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis')),
                ('farmaciaDetalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDetalle01', to='farmacia.FarmaciaDetalle')),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3453', to='planta.Planta')),
                ('viaAdministracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion')),
            ],
        ),
        migrations.AddField(
            model_name='despachos',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaDespacho02', to='farmacia.Farmacia'),
        ),
        migrations.AddField(
            model_name='despachos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm02', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='despachos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3452', to='planta.Planta'),
        ),
    ]
