# Generated by Django 2.1.15 on 2025-07-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0019_auto_20250714_0816'),
        ('farmacia', '0002_auto_20250703_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='tipoOrden',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria04', to='enfermeria.EnfermeriaTipoOrigen'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria05', to='enfermeria.EnfermeriaTipoMovimiento'),
        ),
    ]
