# Generated by Django 2.1.15 on 2025-07-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0019_auto_20250714_0816'),
        ('clinico', '0123_auto_20250519_1153'),
        ('facturacion', '0085_auto_20250519_1543'),
        ('sitios', '0023_salas_tiposala'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('farmacia', '0003_auto_20250714_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despachos',
            new_name='FarmaciaDespachos',
        ),
        migrations.RenameModel(
            old_name='FarmaciaDispensa',
            new_name='FarmaciaDespachosDispensa',
        ),
    ]
