# Generated by Django 2.1.15 on 2025-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_auto_20250714_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='item',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
