# Generated by Django 2.1.15 on 2025-07-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('farmacia', '0005_farmaciadespachosdispensa_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica390', to='sitios.SedesClinica'),
        ),
    ]
