# Generated by Django 2.1.15 on 2025-07-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('farmacia', '0006_farmacia_sedesclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmaciaEstados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='A', max_length=50)),
                ('estadoReg', models.CharField(blank=True, default='A', editable=False, max_length=1, null=True)),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3459', to='planta.Planta')),
            ],
        ),
    ]
