# Generated by Django 2.1.15 on 2025-07-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_farmaciaestados'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmaciaestados01', to='farmacia.FarmaciaEstados'),
        ),
    ]
