# Generated by Django 2.1.15 on 2025-07-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0023_salas_tiposala'),
        ('planta', '0010_remove_planta_serviciosadministrativos'),
        ('farmacia', '0008_farmacia_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmaciadespachos',
            old_name='serviciosAdministrativos',
            new_name='serviciosAdministrativosEntrega',
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm03', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3472', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3473', to='planta.Planta'),
        ),
    ]
