# Generated by Django 2.1.15 on 2025-07-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_auto_20250716_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciadespachosdispensa',
            name='diasTratamiento',
        ),
        migrations.RemoveField(
            model_name='farmaciadespachosdispensa',
            name='frecuencia',
        ),
    ]
