# Generated by Django 2.1.15 on 2025-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_auto_20250716_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciadespachosdispensa',
            name='item',
        ),
        migrations.RemoveField(
            model_name='farmaciadetalle',
            name='diasTratamiento',
        ),
        migrations.RemoveField(
            model_name='farmaciadetalle',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='consecutivoMedicamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='consecutivoMedicamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
