# Generated by Django 2.1.15 on 2025-07-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_auto_20250717_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciadespachosdispensa',
            name='consecutivoMedicamento',
        ),
    ]
