# Generated by Django 2.1.15 on 2025-07-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0042_ingresos_serviciosadministrativos'),
        ('farmacia', '0012_remove_farmaciadespachosdispensa_consecutivomedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='ingresoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ingreso988', to='admisiones.Ingresos'),
        ),
    ]
