# Generated by Django 2.1.15 on 2025-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_farmacia_ingresopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='cantidadDevuelta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='netoCantidad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
