# Generated by Django 2.1.15 on 2025-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_auto_20250725_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciadevolucion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
