# Generated by Django 2.1.15 on 2025-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_auto_20250729_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='cantidadDevueltaRecibida',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
