# Generated by Django 2.1.15 on 2025-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0017_farmaciadevoluciondetalle_cantidaddevueltarecibida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciadespachos',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciadespachosdispensa',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciadetalle',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciadevolucion',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciadevoluciondetalle',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmaciaestados',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True),
        ),
    ]
