# Generated by Django 2.1.15 on 2025-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0018_auto_20250915_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='ingresoPaciente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
